// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package email

import (
	"gopkg.in/gomail.v2"
)

// Injectors from wire.go:

func InitMailDialer() *gomail.Dialer {
	dialer := NewDialer()
	return dialer
}
