# mysql
[mysql-server]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "775028"
database = "WebMusic"
charset = "utf8mb4"
parseTime = "True"
loc = "Local"
# mysql dev
[mysql-server.dev]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "775028"
database = "WebMusic"
charset = "utf8mb4"
parseTime = "True"
loc = "Local"
# redis
[redis]
host="127.0.0.1"
port="6379"
password="775028"
database=0
maxActiveConns=100
maxIdleConns=10
[static-files-path]
path="/Users/acaibird/Documents/CodeExperimentSpace/Go/Game/public/"
[log-path]
path="/Users/acaibird/Documents/CodeExperimentSpace/Go/Game/log"
[email]
host="smtp.qq.com"
user="1262229357@qq.com"
AuthPassword="sukpkmlqdjmqjjff"
port=465
[aliyun]
AccessKeyId="LTAI5tBhPAUsp5NS3C6jjkyZ"
AccessKeySecret="m7dXXK3W1F8FWuk69IkhhwwrTPeUqU"
[aliyun.sms]
SignName="Acaibird博客"
TemplateCode="SMS_298160970"
Domain="dysmsapi.aliyuncs.com"
[RabbitMQ]
user="guest"
password="guest"
host="localhost"
port="5672"