// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package RabbitMQ

import (
	"github.com/rabbitmq/amqp091-go"
)

// Injectors from wire_rabbitmq.go:

func InitAmpq() (*amqp091.Connection, error) {
	connection, err := NewAmqp()
	if err != nil {
		return nil, err
	}
	return connection, nil
}
