// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mysql

import (
	"database/sql"
	"gorm.io/gorm"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitDb() (*sql.DB, error) {
	db, err := Newdb()
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitOrmDb() (*gorm.DB, error) {
	db, err := NewOrmDb()
	if err != nil {
		return nil, err
	}
	return db, nil
}
